[workspace]
members = [
  "latency",
  "throughput",
  "ping",
  "common",
  "logging-derive",
  "XDPing",
]
[workspace.dependencies]
anyhow = "1.0.68" 
quinn = "0.10.2"
rustls = { version = "*", features = ["dangerous_configuration", "quic"] }
