[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
socket2 = { version = "0.4.7", features = ["all"] }
anyhow = "1.0.68"
libc = "0.2.139"
pnet_datalink = "0.31.0"
tokio = {version = "*", features=["full"]}
nix = "0.26.2"
rcgen = "0.10.0"
quinn = {git = "https://github.com/suhrm/quinn.git", branch = "main"}
rustls = { version = "*", features = ["dangerous_configuration", "quic"] }
logging-macro = {path = "../logging-derive"}
linux-raw-sys = { version = "0.6.1", features = ["net"] }

