name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: rustup update && rustup default nightly && cargo install cargo-limit
    - name: Build
      run: cargo lbuild
    - name: Run tests
      run: cargo ltest -- --nocapture
